{{- if and .Values.ssh.privateKey (not .Values.ssh.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencode.gitSshSecretName" . }}
  labels:
    {{- include "opencode.labels" . | nindent 4 }}
    app.kubernetes.io/component: git-ssh
type: Opaque
stringData:
  {{ .Values.ssh.key }}: |
    {{- .Values.ssh.privateKey | nindent 4 }}
{{- end }}
