{{- if .Values.imageCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencode.imagePullSecretName" . }}
  labels:
    {{- include "opencode.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "opencode.dockerconfigjson" . | b64enc | quote }}
{{- end }}
